# Generated by Django 3.2.8 on 2021-10-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookType', models.CharField(choices=[('F', 'Fantasy'), ('A', 'Adventure'), ('SCI', 'Science Fiction'), ('BIO', 'Biography'), ('HOR', 'Horror'), ('HIS', 'History'), ('NOV', 'Novel'), ('ROM', 'Romance'), ('NF', 'Non fiction'), ('SC', 'Science'), ('EC', 'Economics'), ('SH', 'SHORT STORY'), ('PO', 'Poetry')], max_length=3)),
            ],
        ),
    ]
