# Generated by Django 3.2.8 on 2021-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='bookType',
            field=models.CharField(max_length=20),
        ),
    ]
