# Generated by Django 3.2.8 on 2021-10-19 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_booktype_booktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktype',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
