# Generated by Django 3.2.8 on 2021-10-19 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_booktype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='user',
            field=models.ManyToManyField(related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
