# Generated by Django 3.2.8 on 2021-10-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_booktype_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktype',
            old_name='bookType',
            new_name='name',
        ),
    ]
