# Generated by Django 3.2.8 on 2021-10-20 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_rename_booktype_booktype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', multiselectfield.db.fields.MultiSelectField(choices=[('FANTASY', 'Fantasy'), ('ADVENTURE', 'Adventure'), ('SCI_FI', 'Science Fiction'), ('BIOGRAPHY', 'Biography'), ('HORROR', 'Horror'), ('HISTORY', 'History'), ('NOVEL', 'Novel'), ('ROMANCE', 'Romance'), ('NON_FIC', 'Non fiction'), ('SCIENCE', 'Science'), ('ECONOMICS', 'Novel'), ('CLASSICS', 'Classics')], max_length=98)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
