# Generated by Django 3.2.8 on 2021-10-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bookinterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookType',
        ),
    ]
