# Generated by Django 3.2.8 on 2021-10-20 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
