# Generated by Django 3.2.8 on 2021-10-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookAuthor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='bookTitle',
            field=models.CharField(max_length=100),
        ),
    ]
