# Generated by Django 3.2.8 on 2021-10-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bookcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_cover', to='blog.post'),
        ),
    ]
