# Generated by Django 3.2.8 on 2021-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_bookcover_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='image',
            field=models.ImageField(default='default_cover.jpg', upload_to='book_covers'),
        ),
    ]
